---
blank_issues_enabled: false
contact_links:
  - name: ADServiceAccountManager Community Support
    url: https://github.com/michaelmsonne/ADServiceAccountManager/discussions
    about: Please ask and answer questions here.
